package com.amparo.amparoapi.domain.enums

enum class HealthInsuranceType(val description: String) {
    ALLIANZ("Allianz Saúde"),
    AMEPLAN("Ameplan Saúde"),
    AMIL_SAUDE("Amil Saúde"),
    BIOSAUDE("BioSaúde"),
    BIOVIDA_SAUDE("BioVida Saúde"),
    BLUE_MED_SAUDE("Blue Med Saúde"),
    BRADESCO_SAUDE("Bradesco Saúde"),
    CLASSES_LABORIOSAS("Classes Laboriosas"),
    CRUZ_AZUL_SAUDE("Cruz Azul"),
    GS_SAUDE("GS Saúde"),
    GOLDEN_CROSS("Golden Cross"),
    HAPVIDA("HapVida"),
    HEALTH_SANITARIS("Health Sanitaris"),
    INTERCLINICAS_SAUDE("Interclínicas Saúde"),
    MEDICAL_HEALTH("Medical Health"),
    MED_TOUR_SAUDE("Med Tour Saúde"),
    NOTRE_DAME_INTERMEDICA("Notre Dame Intermédica"),
    PLANSAUDE("PlanSaúde"),
    PLENA_SAUDE("Plena Saúde"),
    PORTO_SEGURO_SAUDE("Porto Seguro Saúde"),
    PREVENT_SENIOR("Prevent Senior"),
    QSAUDE("QSaúde"),
    SANTA_HELENA_SAUDE("Santa Helena Saúde"),
    SAO_CRISTOVAO_SAUDE("São Cristóvão Saúde"),
    SAO_MIGUEL_SAUDE("São Miguel Saúde"),
    SEGUROS_UNIMED("Seguros Unimed"),
    SOMPO_SAUDE("Sompo Saúde"),
    SUL_AMERICA_SAUDE("Sul América Saúde"),
    TOTAL_MEDCARE_SAUDE("Total Medcare Saúde"),
    TRASMONTANO_SAUDE("Trasmontano Saúde"),
    UNIHOSP_SAUDE("Unihosp Saúde"),
    UNIMED("Unimed")
}